name: Deploy to Server

on:
  push:
    branches:
      - main # Change to your branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install Node.js and dependencies
        uses: actions/setup-node@v2
        with:
          node-version: "14"

      - name: Build and deploy application
        run: |
          npm install
          npm run build
          scp -r build/* ec2-user@13.60.55.185:/usr/share/nginx/html/build/
          ssh ec2-user@13.60.55.185 'sudo systemctl restart nginx'
        env:
          SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
